// source: v1/cluster.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.teleport.terminal.v1.ACL', null, global);
goog.exportSymbol('proto.teleport.terminal.v1.Access', null, global);
goog.exportSymbol('proto.teleport.terminal.v1.Cluster', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.teleport.terminal.v1.Cluster = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.teleport.terminal.v1.Cluster, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.teleport.terminal.v1.Cluster.displayName = 'proto.teleport.terminal.v1.Cluster';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.teleport.terminal.v1.Access = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.teleport.terminal.v1.Access, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.teleport.terminal.v1.Access.displayName = 'proto.teleport.terminal.v1.Access';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.teleport.terminal.v1.ACL = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.teleport.terminal.v1.ACL.repeatedFields_, null);
};
goog.inherits(proto.teleport.terminal.v1.ACL, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.teleport.terminal.v1.ACL.displayName = 'proto.teleport.terminal.v1.ACL';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.teleport.terminal.v1.Cluster.prototype.toObject = function(opt_includeInstance) {
  return proto.teleport.terminal.v1.Cluster.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.teleport.terminal.v1.Cluster} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.teleport.terminal.v1.Cluster.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    connected: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    acl: (f = msg.getAcl()) && proto.teleport.terminal.v1.ACL.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.teleport.terminal.v1.Cluster}
 */
proto.teleport.terminal.v1.Cluster.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.teleport.terminal.v1.Cluster;
  return proto.teleport.terminal.v1.Cluster.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.teleport.terminal.v1.Cluster} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.teleport.terminal.v1.Cluster}
 */
proto.teleport.terminal.v1.Cluster.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setConnected(value);
      break;
    case 3:
      var value = new proto.teleport.terminal.v1.ACL;
      reader.readMessage(value,proto.teleport.terminal.v1.ACL.deserializeBinaryFromReader);
      msg.setAcl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.teleport.terminal.v1.Cluster.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.teleport.terminal.v1.Cluster.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.teleport.terminal.v1.Cluster} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.teleport.terminal.v1.Cluster.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConnected();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getAcl();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.teleport.terminal.v1.ACL.serializeBinaryToWriter
    );
  }
};


/**
 * optional string Name = 1;
 * @return {string}
 */
proto.teleport.terminal.v1.Cluster.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.teleport.terminal.v1.Cluster} returns this
 */
proto.teleport.terminal.v1.Cluster.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool Connected = 2;
 * @return {boolean}
 */
proto.teleport.terminal.v1.Cluster.prototype.getConnected = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.teleport.terminal.v1.Cluster} returns this
 */
proto.teleport.terminal.v1.Cluster.prototype.setConnected = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional ACL ACL = 3;
 * @return {?proto.teleport.terminal.v1.ACL}
 */
proto.teleport.terminal.v1.Cluster.prototype.getAcl = function() {
  return /** @type{?proto.teleport.terminal.v1.ACL} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ACL, 3));
};


/**
 * @param {?proto.teleport.terminal.v1.ACL|undefined} value
 * @return {!proto.teleport.terminal.v1.Cluster} returns this
*/
proto.teleport.terminal.v1.Cluster.prototype.setAcl = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.Cluster} returns this
 */
proto.teleport.terminal.v1.Cluster.prototype.clearAcl = function() {
  return this.setAcl(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.Cluster.prototype.hasAcl = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.teleport.terminal.v1.Access.prototype.toObject = function(opt_includeInstance) {
  return proto.teleport.terminal.v1.Access.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.teleport.terminal.v1.Access} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.teleport.terminal.v1.Access.toObject = function(includeInstance, msg) {
  var f, obj = {
    list: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    read: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    edit: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    create: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    pb_delete: jspb.Message.getBooleanFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.Access.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.teleport.terminal.v1.Access;
  return proto.teleport.terminal.v1.Access.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.teleport.terminal.v1.Access} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.Access.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setList(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRead(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEdit(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCreate(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDelete(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.teleport.terminal.v1.Access.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.teleport.terminal.v1.Access.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.teleport.terminal.v1.Access} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.teleport.terminal.v1.Access.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getList();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getRead();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getEdit();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getCreate();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getDelete();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional bool List = 1;
 * @return {boolean}
 */
proto.teleport.terminal.v1.Access.prototype.getList = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.teleport.terminal.v1.Access} returns this
 */
proto.teleport.terminal.v1.Access.prototype.setList = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool Read = 2;
 * @return {boolean}
 */
proto.teleport.terminal.v1.Access.prototype.getRead = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.teleport.terminal.v1.Access} returns this
 */
proto.teleport.terminal.v1.Access.prototype.setRead = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool Edit = 3;
 * @return {boolean}
 */
proto.teleport.terminal.v1.Access.prototype.getEdit = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.teleport.terminal.v1.Access} returns this
 */
proto.teleport.terminal.v1.Access.prototype.setEdit = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool Create = 4;
 * @return {boolean}
 */
proto.teleport.terminal.v1.Access.prototype.getCreate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.teleport.terminal.v1.Access} returns this
 */
proto.teleport.terminal.v1.Access.prototype.setCreate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool Delete = 5;
 * @return {boolean}
 */
proto.teleport.terminal.v1.Access.prototype.getDelete = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.teleport.terminal.v1.Access} returns this
 */
proto.teleport.terminal.v1.Access.prototype.setDelete = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.teleport.terminal.v1.ACL.repeatedFields_ = [12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.teleport.terminal.v1.ACL.prototype.toObject = function(opt_includeInstance) {
  return proto.teleport.terminal.v1.ACL.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.teleport.terminal.v1.ACL} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.teleport.terminal.v1.ACL.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessions: (f = msg.getSessions()) && proto.teleport.terminal.v1.Access.toObject(includeInstance, f),
    authconnectors: (f = msg.getAuthconnectors()) && proto.teleport.terminal.v1.Access.toObject(includeInstance, f),
    roles: (f = msg.getRoles()) && proto.teleport.terminal.v1.Access.toObject(includeInstance, f),
    users: (f = msg.getUsers()) && proto.teleport.terminal.v1.Access.toObject(includeInstance, f),
    trustedclusters: (f = msg.getTrustedclusters()) && proto.teleport.terminal.v1.Access.toObject(includeInstance, f),
    events: (f = msg.getEvents()) && proto.teleport.terminal.v1.Access.toObject(includeInstance, f),
    tokens: (f = msg.getTokens()) && proto.teleport.terminal.v1.Access.toObject(includeInstance, f),
    servers: (f = msg.getServers()) && proto.teleport.terminal.v1.Access.toObject(includeInstance, f),
    appservers: (f = msg.getAppservers()) && proto.teleport.terminal.v1.Access.toObject(includeInstance, f),
    dbservers: (f = msg.getDbservers()) && proto.teleport.terminal.v1.Access.toObject(includeInstance, f),
    kubeservers: (f = msg.getKubeservers()) && proto.teleport.terminal.v1.Access.toObject(includeInstance, f),
    sshloginsList: (f = jspb.Message.getRepeatedField(msg, 12)) == null ? undefined : f,
    accessrequests: (f = msg.getAccessrequests()) && proto.teleport.terminal.v1.Access.toObject(includeInstance, f),
    billing: (f = msg.getBilling()) && proto.teleport.terminal.v1.Access.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.teleport.terminal.v1.ACL}
 */
proto.teleport.terminal.v1.ACL.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.teleport.terminal.v1.ACL;
  return proto.teleport.terminal.v1.ACL.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.teleport.terminal.v1.ACL} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.teleport.terminal.v1.ACL}
 */
proto.teleport.terminal.v1.ACL.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.teleport.terminal.v1.Access;
      reader.readMessage(value,proto.teleport.terminal.v1.Access.deserializeBinaryFromReader);
      msg.setSessions(value);
      break;
    case 2:
      var value = new proto.teleport.terminal.v1.Access;
      reader.readMessage(value,proto.teleport.terminal.v1.Access.deserializeBinaryFromReader);
      msg.setAuthconnectors(value);
      break;
    case 3:
      var value = new proto.teleport.terminal.v1.Access;
      reader.readMessage(value,proto.teleport.terminal.v1.Access.deserializeBinaryFromReader);
      msg.setRoles(value);
      break;
    case 4:
      var value = new proto.teleport.terminal.v1.Access;
      reader.readMessage(value,proto.teleport.terminal.v1.Access.deserializeBinaryFromReader);
      msg.setUsers(value);
      break;
    case 5:
      var value = new proto.teleport.terminal.v1.Access;
      reader.readMessage(value,proto.teleport.terminal.v1.Access.deserializeBinaryFromReader);
      msg.setTrustedclusters(value);
      break;
    case 6:
      var value = new proto.teleport.terminal.v1.Access;
      reader.readMessage(value,proto.teleport.terminal.v1.Access.deserializeBinaryFromReader);
      msg.setEvents(value);
      break;
    case 7:
      var value = new proto.teleport.terminal.v1.Access;
      reader.readMessage(value,proto.teleport.terminal.v1.Access.deserializeBinaryFromReader);
      msg.setTokens(value);
      break;
    case 8:
      var value = new proto.teleport.terminal.v1.Access;
      reader.readMessage(value,proto.teleport.terminal.v1.Access.deserializeBinaryFromReader);
      msg.setServers(value);
      break;
    case 9:
      var value = new proto.teleport.terminal.v1.Access;
      reader.readMessage(value,proto.teleport.terminal.v1.Access.deserializeBinaryFromReader);
      msg.setAppservers(value);
      break;
    case 10:
      var value = new proto.teleport.terminal.v1.Access;
      reader.readMessage(value,proto.teleport.terminal.v1.Access.deserializeBinaryFromReader);
      msg.setDbservers(value);
      break;
    case 11:
      var value = new proto.teleport.terminal.v1.Access;
      reader.readMessage(value,proto.teleport.terminal.v1.Access.deserializeBinaryFromReader);
      msg.setKubeservers(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.addSshlogins(value);
      break;
    case 13:
      var value = new proto.teleport.terminal.v1.Access;
      reader.readMessage(value,proto.teleport.terminal.v1.Access.deserializeBinaryFromReader);
      msg.setAccessrequests(value);
      break;
    case 14:
      var value = new proto.teleport.terminal.v1.Access;
      reader.readMessage(value,proto.teleport.terminal.v1.Access.deserializeBinaryFromReader);
      msg.setBilling(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.teleport.terminal.v1.ACL.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.teleport.terminal.v1.ACL.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.teleport.terminal.v1.ACL} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.teleport.terminal.v1.ACL.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessions();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.teleport.terminal.v1.Access.serializeBinaryToWriter
    );
  }
  f = message.getAuthconnectors();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.teleport.terminal.v1.Access.serializeBinaryToWriter
    );
  }
  f = message.getRoles();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.teleport.terminal.v1.Access.serializeBinaryToWriter
    );
  }
  f = message.getUsers();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.teleport.terminal.v1.Access.serializeBinaryToWriter
    );
  }
  f = message.getTrustedclusters();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.teleport.terminal.v1.Access.serializeBinaryToWriter
    );
  }
  f = message.getEvents();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.teleport.terminal.v1.Access.serializeBinaryToWriter
    );
  }
  f = message.getTokens();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.teleport.terminal.v1.Access.serializeBinaryToWriter
    );
  }
  f = message.getServers();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.teleport.terminal.v1.Access.serializeBinaryToWriter
    );
  }
  f = message.getAppservers();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.teleport.terminal.v1.Access.serializeBinaryToWriter
    );
  }
  f = message.getDbservers();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.teleport.terminal.v1.Access.serializeBinaryToWriter
    );
  }
  f = message.getKubeservers();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.teleport.terminal.v1.Access.serializeBinaryToWriter
    );
  }
  f = message.getSshloginsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      12,
      f
    );
  }
  f = message.getAccessrequests();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      proto.teleport.terminal.v1.Access.serializeBinaryToWriter
    );
  }
  f = message.getBilling();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      proto.teleport.terminal.v1.Access.serializeBinaryToWriter
    );
  }
};


/**
 * optional Access Sessions = 1;
 * @return {?proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.ACL.prototype.getSessions = function() {
  return /** @type{?proto.teleport.terminal.v1.Access} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.Access, 1));
};


/**
 * @param {?proto.teleport.terminal.v1.Access|undefined} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
*/
proto.teleport.terminal.v1.ACL.prototype.setSessions = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearSessions = function() {
  return this.setSessions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ACL.prototype.hasSessions = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Access AuthConnectors = 2;
 * @return {?proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.ACL.prototype.getAuthconnectors = function() {
  return /** @type{?proto.teleport.terminal.v1.Access} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.Access, 2));
};


/**
 * @param {?proto.teleport.terminal.v1.Access|undefined} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
*/
proto.teleport.terminal.v1.ACL.prototype.setAuthconnectors = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearAuthconnectors = function() {
  return this.setAuthconnectors(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ACL.prototype.hasAuthconnectors = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Access Roles = 3;
 * @return {?proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.ACL.prototype.getRoles = function() {
  return /** @type{?proto.teleport.terminal.v1.Access} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.Access, 3));
};


/**
 * @param {?proto.teleport.terminal.v1.Access|undefined} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
*/
proto.teleport.terminal.v1.ACL.prototype.setRoles = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearRoles = function() {
  return this.setRoles(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ACL.prototype.hasRoles = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Access Users = 4;
 * @return {?proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.ACL.prototype.getUsers = function() {
  return /** @type{?proto.teleport.terminal.v1.Access} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.Access, 4));
};


/**
 * @param {?proto.teleport.terminal.v1.Access|undefined} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
*/
proto.teleport.terminal.v1.ACL.prototype.setUsers = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearUsers = function() {
  return this.setUsers(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ACL.prototype.hasUsers = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Access TrustedClusters = 5;
 * @return {?proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.ACL.prototype.getTrustedclusters = function() {
  return /** @type{?proto.teleport.terminal.v1.Access} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.Access, 5));
};


/**
 * @param {?proto.teleport.terminal.v1.Access|undefined} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
*/
proto.teleport.terminal.v1.ACL.prototype.setTrustedclusters = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearTrustedclusters = function() {
  return this.setTrustedclusters(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ACL.prototype.hasTrustedclusters = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional Access Events = 6;
 * @return {?proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.ACL.prototype.getEvents = function() {
  return /** @type{?proto.teleport.terminal.v1.Access} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.Access, 6));
};


/**
 * @param {?proto.teleport.terminal.v1.Access|undefined} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
*/
proto.teleport.terminal.v1.ACL.prototype.setEvents = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearEvents = function() {
  return this.setEvents(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ACL.prototype.hasEvents = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional Access Tokens = 7;
 * @return {?proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.ACL.prototype.getTokens = function() {
  return /** @type{?proto.teleport.terminal.v1.Access} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.Access, 7));
};


/**
 * @param {?proto.teleport.terminal.v1.Access|undefined} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
*/
proto.teleport.terminal.v1.ACL.prototype.setTokens = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearTokens = function() {
  return this.setTokens(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ACL.prototype.hasTokens = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Access Servers = 8;
 * @return {?proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.ACL.prototype.getServers = function() {
  return /** @type{?proto.teleport.terminal.v1.Access} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.Access, 8));
};


/**
 * @param {?proto.teleport.terminal.v1.Access|undefined} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
*/
proto.teleport.terminal.v1.ACL.prototype.setServers = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearServers = function() {
  return this.setServers(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ACL.prototype.hasServers = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional Access AppServers = 9;
 * @return {?proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.ACL.prototype.getAppservers = function() {
  return /** @type{?proto.teleport.terminal.v1.Access} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.Access, 9));
};


/**
 * @param {?proto.teleport.terminal.v1.Access|undefined} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
*/
proto.teleport.terminal.v1.ACL.prototype.setAppservers = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearAppservers = function() {
  return this.setAppservers(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ACL.prototype.hasAppservers = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional Access DBServers = 10;
 * @return {?proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.ACL.prototype.getDbservers = function() {
  return /** @type{?proto.teleport.terminal.v1.Access} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.Access, 10));
};


/**
 * @param {?proto.teleport.terminal.v1.Access|undefined} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
*/
proto.teleport.terminal.v1.ACL.prototype.setDbservers = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearDbservers = function() {
  return this.setDbservers(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ACL.prototype.hasDbservers = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional Access KubeServers = 11;
 * @return {?proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.ACL.prototype.getKubeservers = function() {
  return /** @type{?proto.teleport.terminal.v1.Access} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.Access, 11));
};


/**
 * @param {?proto.teleport.terminal.v1.Access|undefined} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
*/
proto.teleport.terminal.v1.ACL.prototype.setKubeservers = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearKubeservers = function() {
  return this.setKubeservers(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ACL.prototype.hasKubeservers = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * repeated string SSHLogins = 12;
 * @return {!Array<string>}
 */
proto.teleport.terminal.v1.ACL.prototype.getSshloginsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 12));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.setSshloginsList = function(value) {
  return jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.addSshlogins = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearSshloginsList = function() {
  return this.setSshloginsList([]);
};


/**
 * optional Access AccessRequests = 13;
 * @return {?proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.ACL.prototype.getAccessrequests = function() {
  return /** @type{?proto.teleport.terminal.v1.Access} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.Access, 13));
};


/**
 * @param {?proto.teleport.terminal.v1.Access|undefined} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
*/
proto.teleport.terminal.v1.ACL.prototype.setAccessrequests = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearAccessrequests = function() {
  return this.setAccessrequests(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ACL.prototype.hasAccessrequests = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional Access Billing = 14;
 * @return {?proto.teleport.terminal.v1.Access}
 */
proto.teleport.terminal.v1.ACL.prototype.getBilling = function() {
  return /** @type{?proto.teleport.terminal.v1.Access} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.Access, 14));
};


/**
 * @param {?proto.teleport.terminal.v1.Access|undefined} value
 * @return {!proto.teleport.terminal.v1.ACL} returns this
*/
proto.teleport.terminal.v1.ACL.prototype.setBilling = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ACL} returns this
 */
proto.teleport.terminal.v1.ACL.prototype.clearBilling = function() {
  return this.setBilling(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ACL.prototype.hasBilling = function() {
  return jspb.Message.getField(this, 14) != null;
};


goog.object.extend(exports, proto.teleport.terminal.v1);
